clc;clear all;close all;
F=8;M=2;K=16;B=4;
x0=4;
sim('muskaan',30);
plot(t,x);
hold on;
B=8;
sim('muskaan',30);
plot(t,x,'r');
hold on;
B=12;
sim('muskaan',30);
plot(t,x,'g');
B=25;
sim('muskaan',30);
plot(t,x,'m');
xlabel('time');
ylabel('value of x');
title('Mass Spring Example-3064');
legend('B=4','B=8','B=12','B=25');